BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "characters" (
	"id"	INTEGER,
	"username"	TEXT NOT NULL UNIQUE,
	"password"	TEXT NOT NULL,
	"email"	TEXT NOT NULL DEFAULT '',
	"register_date"	INTEGER NOT NULL DEFAULT 0,
	"register_ip"	TEXT,
	"rank"	INTEGER NOT NULL DEFAULT 0,
	"decibels"	INTEGER NOT NULL DEFAULT 0,
	"is_female"	INTEGER NOT NULL DEFAULT 0,
	"skin_tone"	INTEGER NOT NULL DEFAULT 2,
	"face_index"	INTEGER NOT NULL DEFAULT 0,
	"hair_index"	INTEGER NOT NULL DEFAULT 0,
	"hair_colour"	INTEGER NOT NULL DEFAULT 0,
	"shirt_index"	INTEGER NOT NULL DEFAULT 0,
	"shirt_colour"	INTEGER NOT NULL DEFAULT 8352044,
	"pants_index"	INTEGER NOT NULL DEFAULT 0,
	"pants_colour"	INTEGER NOT NULL DEFAULT 2398539,
	"shoes_index"	INTEGER NOT NULL DEFAULT 0,
	"shoes_colour"	INTEGER NOT NULL DEFAULT 8345652,
	"inventory"	TEXT NOT NULL DEFAULT '[]',
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "chat" (
	"id"	INTEGER,
	"character_id"	INTEGER NOT NULL,
	"room_id"	INTEGER NOT NULL,
	"colour"	TEXT,
	"x"	INTEGER NOT NULL DEFAULT 0,
	"y"	INTEGER NOT NULL DEFAULT 0,
	"message"	TEXT NOT NULL DEFAULT '',
	FOREIGN KEY("character_id") REFERENCES "characters"("id"),
	FOREIGN KEY("room_id") REFERENCES "rooms"("id"),
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "rooms" (
	"id"	INTEGER,
	"owner_id"	INTEGER NOT NULL,
	"studio"	TEXT NOT NULL,
	"name"	TEXT NOT NULL DEFAULT 'studio_a',
	"tile"	TEXT,
	"wall"	TEXT,
	"objects"	TEXT NOT NULL DEFAULT '[]',
	"rugs"	TEXT NOT NULL DEFAULT '[]',
	"posters"	TEXT NOT NULL DEFAULT '[]',
	FOREIGN KEY("owner_id") REFERENCES "characters"("id"),
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
